### ISSUE TITLE
Give the option to prevent functions being invoked by their public URL

### ISSUE THREAD

**Issue by DriesCruyskens** [openfaas/faas#1730] opened 2022-06-02 17:41 UTC
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?
Some functions should not be able to get triggered by an HTTP request. In my case it concerns scheduled functions (cron-connector) that should only run once a day. Unless I am mistaken, every function is callable using their public url. This makes functions susceptible to being called on accident or even by bots.

## Expected Behaviour

Functions should have the option of being callable by public URL or not.

## Current Behaviour

Every function gets assigned a public URL.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No, but owner of Serverless for Everyone Else

## List All Possible Solutions and Workarounds

1. Add yaml entry that disables a functions public URL.

2. Have a way to discern between event-connectors IN the function. Say using an environment variable. This way the function can return early when it detects it's being invoked in the wrong way.

3. Find a workaround and add it to the documentation.

## Which Solution Do You Recommend?

1. Add yaml entry that disables a functions public URL.

## Steps to Reproduce (for bugs)

n/a

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.14.2

* Docker version `docker version` (e.g. Docker 17.0.05 ): Docker version 20.10.10, build b485636

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? faasd

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS 12.3.1, m1 Macbook Pro

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment] 2022-06-09 13:12
Hi,

Thanks for leaving the context about what you're trying to do.

Unfortunately, you deleted important parts of the issue template, so I'd ask you to add those back in now.

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

Alex

**Comment by alexellis** [comment] 2022-06-22 14:16
Hi @DriesCruyskens 

We recommend using authentication for functions which are sensitive.

There is no practical way to hide functions on the OpenFaaS gateway, since it is the only way that we recommend to access a function, whether you consider it private or public.

So, that brings me on to my preferred solution at present.

Wherever possible, always use authentication - shared secrets, OAuth clients, etc.

For when you have functions that are called by the cron-connector, it has no way to send authentication, therefore, I would suggest you hide the gateway from the Internet completely.

Then just expose what you want the Internet to access.

You can create an Ingress record for a domain and one TLS cert for each of them or for a specific path on a single domain and only use one TLS cert for all of them.

We have provided FunctionIngress for you to achieve this: https://docs.openfaas.com/reference/ssl/kubernetes-with-cert-manager/#20-tls-and-custom-domains-for-functions

![private-mapped](https://user-images.githubusercontent.com/6358735/175051295-c0c019ef-cab9-4287-938e-c9a131396b31.png)

I'll close this issue as resolved / as designed, however feel free to keep the discussion going.

Regards,

Alex

**Closed by alexellis** 2022-06-22 14:16 UTC
