### ISSUE TITLE
faas-cli fails to build my Go serverless app

### ISSUE THREAD

**Issue by lapwat** [openfaas/faas#681] opened 2018-05-09 15:48 UTC
Running `faas-cli build -f function.yml` fails.

I go into `build/function/` folder & try to build manually the openfaas container with 'docker build . -t function'. I notice that this line is at fault:

`RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }`

If I comment this line, a manual build and `faas-cli deploy` work well. I do not understand what this line checks and why it is useful since my app works well without it.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 18.04.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment] 2018-05-09 15:57
You need to run gofmt on your code

**Comment by lapwat** [comment] 2018-05-09 16:05
Thank you for your quick response.
I tried in `function` folder:
```
gofmt -s -w
error: cannot use -w with standard input
```
```
gofmt -s -w *.go
(no output)
```
Does this mean that it passed the test ?

**Comment by alexellis** [comment] 2018-05-09 16:43
You should run it on individual files and then try to build again.

**Comment by alexellis** [comment] 2018-05-09 19:35
I'm unable to reproduce the error and I'm reasonably sure that the template is working as expected. I'm  going to close the issue but am happy to keep responding to comments to help you.

**Closed by alexellis** 2018-05-09 19:35 UTC

**Comment by lapwat** [comment] 2018-05-10 10:02
I have [pushed the folder](https://github.com/lapwat/project) for you to try to reproduce the error. Can you take a look at it when you have time ?
Thank you

**Comment by lapwat** [comment] 2018-05-11 11:13
You were right, the error was that my code was not formatted correctly. Thanks for your help.

**Comment by alexellis** [comment] 2018-05-11 12:13
That's awesome - have fun and feel free to join the Slack community to keep in touch.

**Comment by alexellis** [comment] 2018-05-11 12:13
Derek lock: resolved
