### ISSUE TITLE
functions are not running in parallel

### ISSUE THREAD

**Issue by avielb** [openfaas/faas#1008] opened 2019-01-01 09:34 UTC
I have deployed a function to OpenFaaS that runs for 30 seconds. if I invoke the function for 10 times in 0.5 seconds interval I see that only the last one or two functions are finished successfully and not interrupted. 

## Expected Behaviour

All of the invocations suppose to finish successfully 
## Current Behaviour

Only last invoked functions are finished successfully and not interrupted.

## Steps to Reproduce (for bugs)

1. create a function that runs for 30 seconds and then return the date 
2. invoke it 10 times in 0.5 seconds interval.

## Context

I am trying to migrate a lambda function from AWS to openfaas. The function performs a specific task and being invoked hundreds of times a minute  every time with different task args. when trying to get it to work with openfaas I am having the issue as described.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Version: 0.6.12
* Docker version `docker version` (e.g. Docker 17.0.05 ):
I am using AWS EKS. 

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by alexellis** [comment] 2019-01-01 10:10
This is a supported use-case with OpenFaaS so I'm going to close the issue - please do keep commenting though and if any issue is found we'll reopen or raise a specific issue. 

Please see how to configure your timeouts using the instructions in the troubleshooting guide. Providing a GitHub repo would also be ideal for helping reproduce the issue mentioned.

https://docs.openfaas.com/deployment/troubleshooting/

Alex

**Closed by alexellis** 2019-01-01 10:10 UTC

**Comment by viveksyngh** [comment] 2019-01-03 06:13
@avielb Looks like you have not setup timeout values for function.

Default `read_timeout` and `write_timeout` value for functions are 5 seconds (subject to change) and can be overridden using `read_timeout` and `write_timeout` environment variable for each function.

If these values are not more than time function takes to execute, function will timeout and give `502 Bad Gateway` response.
