### ISSUE TITLE
incorrect http upstream timeout message

### ISSUE THREAD

**Issue by leongold** [openfaas/faas#1630] opened 2021-02-11 08:27 UTC
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

With our nginx ingress timing out (60s) during a function, the following was logged:

```
[ml-walls-59d7fbb4c8-bb4jh] 2021/02/10 17:00:27 stderr: 2021-02-10 17:00:27,720 [INFO] ml-walls: sleeping: 600 
[ml-walls-59d7fbb4c8-bb4jh] 2021/02/10 17:00:27 stderr: INFO:ml-walls:sleeping: 600 
[ml-walls-59d7fbb4c8-bb4jh] 2021/02/10 17:01:27 Upstream HTTP request error: Post http://127.0.0.1:5005/sleep: context canceled 
[ml-walls-59d7fbb4c8-bb4jh] 2021/02/10 17:01:27 Upstream HTTP killed due to exec_timeout: 3m5s 
```
Both the reason (function's `exec_timeout`) and the elapsed time (3m5s) are incorrect. 

## Expected Behaviour
The timeout message doesn't contain incorrect information. 

## Current Behaviour
An incorrect message containing incorrect reason & duration is being logged.

## Steps to reproduce
We reproduced this by creating a sleep route that sleeps longer than nginx's 60s timeout.

## Environment:
OpenFaaS 0.20.7 on top of EKS 1.18

**Comment by alexellis** [comment] 2021-02-11 08:54
Thank you for your interest in OpenFaaS.

There's a few things we need before we can start looking into your issue, or providing help. I'll try to give you a few starting points, but you will also need to do your bit to help us, help you.

You talk about "our" as if we (the community) would know who you are. Please see: [First impressions - introducing yourself and your use-case](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#first-impressions---introducing-yourself-and-your-use-case)

Could you give yourself or group a quick intro?

You have missed out "Context" which lets us know how this is affecting you and more about the problem you're trying to solve with this combination of technology.

The steps provided under Steps to reproduce are not actionable, so I would ask you to give step-by-step instructions or close the issue.

You may also find it useful to look up how to use [Extended timeouts](https://docs.openfaas.com/tutorials/expanded-timeouts/) in the project docs.

**Comment by alexellis** [comment] 2021-02-24 14:11
Closing due to lack of information.

**Closed** 2021-02-24 14:11 UTC
