### ISSUE TITLE
`curl -sSL https://cli.openfaas.com | sh` command fails with an error

### ISSUE THREAD

**Issue by alexburykin** [openfaas/faas#1615] opened 2021-01-13 10:40 UTC
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

## Expected Behaviour

Script download the latest version of faas-cli and installs it

## Current Behaviour

Fails with error `https://github.com/openfaas/faas-cli/releases/download/0.12.21socket-worker-5029ae85.js/faas-cli` because of the wrong url

## Possible Solution

Check part in the script that builds `URL` for downloading faas-cli

## Steps to Reproduce (for bugs)

1. Run `curl -sSL https://cli.openfaas.com | sh` in console

## Context

We can't build a new version of our project on CI because docker build fails

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
no faas-cli yet.

* Docker version `docker version` (e.g. Docker 17.0.05 ):
FROM docker:19.03.12-dind

* Are you using Kubernetes or faasd?

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux on CircleCI

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment] 2021-01-13 14:11
Duplicate of: https://github.com/openfaas/cli.openfaas.com/pull/6

Thanks for your interest.

**Closed** 2021-01-13 14:11 UTC
