### ISSUE TITLE
expending template.yml file

### ISSUE THREAD

**Issue by ArieLevs** [openfaas/faas#799] opened 2018-08-02 14:56 UTC
Hi,
functions are running as pods at openfaas-fn namespace,
but there is very poor ability to manipulate these pods, does that makes sense to provide ability to mount volumes to a faas framework?

is there an option to pass Kubernetes secrets as environment vars?

## Expected Behaviour
Able to use Kubernetes deployment syntax on template.yml
example 1: 
Have the ability to add `volumeMounts` and point it to a `persistentVolumeClaim` in the  template.yml file, does that makes sense on a faas?

Using encrypted environment variables
example 2:
Is there an option to provide environment secrets?
```
secrets:
    - secret-password <- need to be used as a env var
environment:
    write_debug: true
    blabla: "some value"
    
```

## Current Behaviour
poor ability to manipulate containers at openfaas-fn namespace

## Context
Using encrypted strings in my functions
Providing my function a local path

## Your Environment
* Docker version: 17.06.2-ce
* Kubernetes
* Operating System and version: Amazon Linux 2 (2017.12) (EKS Cluster)

**Comment by alexellis** [comment] 2018-08-02 16:54
Derek add label: duplicate

**Comment by alexellis** [comment] 2018-08-02 16:56
There are several different questions or suggestions here.

Main suggestion is for volume mounting which is a duplicate of #320 (so will be closed, feel free to +1 or comment there) We recommend using Ceph or Minio for storage in S3 buckets, functions are not stateful so should not have volumes mounted.

Second suggestion: secrets as ENV-vars, this is also a duplicate. Please can you explain why you cannot use the filesystem? Secrets are mounted in a standard location - see the docs for more https://docs.openfaas.com/

Please feel free to keep commenting.

**Comment by alexellis** [comment] 2018-08-02 16:57
Derek close: duplicate

**Closed by alexellis** 2018-08-02 16:57 UTC
Labels: duplicate

**Comment by alexellis** [comment] 2018-08-02 17:01
Here's an example of how you can read a file, and if you want push that into the environment in Python. For Node it'll be almost identical. I recommend against storing secure secrets in environmental variables. 

```python
import os

with open("/var/run/openfaas/secrets/s3-access-key") as f:
    os.environ["S3_ACCESS_KEY"] = f.read().strip()
```

**Comment by alexellis** [comment] 2018-08-05 20:48
Would you like to be listed on our users page because you're a user of OpenFaaS? https://docs.openfaas.com/#users-of-openfaas

Alex

**Comment by ArieLevs** [comment] 2018-08-06 06:45
Hi @alexellis 

We are currently running a POC with OpenFaaS, Let me check this option, will update.
