### ISSUE TITLE
Question - unable to find samples.yml 

### ISSUE THREAD

**Issue by EsrefDurna** [openfaas/faas#629] opened 2018-04-05 03:04 UTC
I'm following 
https://github.com/openfaas/faas/blob/master/guide/deployment_k8s.md

cli examples aren't working.
$ faas-cli deploy -f samples.yml
Please provide a --image to be deployed

or

$faas-cli deploy -f samples.yml --gateway http://192.168.99.100:31112
Please provide a --image to be deployed

**Comment by EsrefDurna** [comment] 2018-04-05 03:07
plus 
another example says
$ faas-cli list  -g http://127.0.0.1:31112

which I tried as below

$ faas-cli list -f http://192.168.99.100:31112
Parsed: http://192.168.99.100:31112
Error with YAML file
Yaml: line 31: mapping values are not allowed in this context

**Comment by BurtonR** [comment] 2018-04-05 03:14
@EsrefDurna Please fill out the new issue template completely. This is there for our benefit and yours. What is the context? Where in the guide are you when you get the error?
What OS are you running?
Docker version? K8s version?
etc...

That said, can you confirm that there is a `samples.yml` file present? 

We've recently updated the repo to use the OpenFaaS standard `stack.yml` file, but it appears the K8s deployment guide has not been updated. Could that be the cause of your troubles?

**Comment by EsrefDurna** [comment] 2018-04-05 04:03
Hello Burton,
Yes sample.yml is there.
yes openfaas is already working fine.
system is ubuntu 16.04

what I tried is to configure faas-cli with yml and that instructions at the read me are buggt.

1-if you see the error message it says that present image, while the read me doesn't mention anything about the image.
2- second comment is also an instruction from read me and its also not working.

Thank you so much

**Comment by ericstoekl** [comment] 2018-04-05 15:56
@EsrefDurna Thank you for reporting this issue. Like @BurtonR mentioned, if there is a `stack.yml` file present in the same directory then the `faas-cli` may be preferring that file over your `samples.yml`.

Can you list out the contents of the directory you are running your `faas-cli deploy` command in? Can you see if moving to a different directory changes the output message?

**Comment by alexellis** [comment] 2018-04-05 16:31
I don't believe you have a samples.yml file in your working directory? We renamed it to stack.yml and the -f parameter is no longer needed, but this isn't the easiest way to learn about OpenFaaS. How about you try the workshop via GitHub.com/OpenFaaS/workshop.

In the meantime one of us will update the Markdown file so it's in sync with the changes made in the CLI repo.

**Comment by EsrefDurna** [comment] 2018-04-06 03:01
I do have samples.yml

$ ls s*
samples.yml  server.go

$  faas-cli deploy -f samples.yml
Please provide a --image to be deployed

**Comment by EsrefDurna** [comment] 2018-04-06 03:02
$ cat samples.yml 
provider:  
  name: faas
  gateway: http://192.168.99.100:31112

**Comment by ericstoekl** [comment] 2018-04-06 03:10
Derek close: @EsrefDurna -- That is your full `samples.yml` file? Looks like it does not actually define a function. Please create a function using the `faas-cli new` command.

Try following the full workshop, in particular this section: https://github.com/openfaas/workshop/blob/master/lab3.md#creating-a-new-function

**Closed by ericstoekl** 2018-04-06 03:10 UTC

**Comment by EsrefDurna** [comment] 2018-04-06 03:16
Thank you @ericstoekl  so please update the documentation because in the documentation is looks like this sample.yml is enough for cli configuration and this empty yml is enough for a deployment.
https://docs.openfaas.com/deployment/kubernetes/

thank you
