### ISSUE TITLE
Hacktoberfast - provide guide for self-hosted registry

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#257] opened 2017-10-05 16:53 UTC
Provide a guide for a self-hosted registry that can be used with OpenFaaS on Swarm and Kubernetes for quick, private deployments of functions.

**Comment by johnmccabe** [comment] 2017-10-09 21:11
Derek add label: duplicate

**Comment by johnmccabe** [comment] 2017-10-09 21:11
Dupe of #242

**Closed** 2017-10-09 21:30 UTC
Labels: duplicate, hacktoberfest
