### ISSUE TITLE
UI does not render JSON responses in certain scenarios

### ISSUE THREAD

**Issue by jrevillas** [openfaas/faas#398] opened 2017-11-18 08:33 UTC
The UI sets a `Content-Type` header on the request to explicitly specify if the payload is a JSON document (`Content-Type: application/json`) or something else (`Content-Type: text/plain`). The request is then sent to the selected function, waiting for a response.

## Expected behaviour
Gateway's UI should render the response data according to the content type of the response. It should make use of `JSON.stringify(...)` to render JSON responses. In any other case, data should be rendered as it comes.

## Current behaviour
The UI relies on request's `Content-Type` to render the response. This causes a serialization error while rendering JSON responses coming as a result of a non-JSON request, showing `[object Object]` in the response field. I've been using the `SentimentAnalysis` function to test this issue.

## Possible solution
We should care about content negotiation to provide different versions of a response (if needed). Functions like `SentimentAnalysys` should return a `Content-Type: application/json` header. Gateway's UI should rely on response's headers and content to render the incoming data.

## Steps to reproduce
1. Deploy `SentimentAnalysis`.
2. Fire a request from the UI.

## Context
I'm currently working to address a fix for this issue.

**Comment by alexellis** [comment] 2017-11-18 09:33
Yes this is by design, you can manually pick the content-type in the UI with the option boxes. Automatic selection based upon content type of the response would be better. Thanks for working on this.

**Comment by alexellis** [comment] 2017-11-25 19:13
Fixed in #399. Cheers

**Closed by alexellis** 2017-11-25 19:13 UTC
