### ISSUE TITLE
Kotlin Native Support

### ISSUE THREAD

**Issue by napperley** [openfaas/faas#709] opened 2018-06-03 09:27 UTC
In OpenFaaS there is no [support](https://github.com/openfaas/faas/tree/master/sample-functions/BaseFunctions) for the [Kotlin](https://kotlinlang.org/) programming language (specifically for Kotlin Native). Unlike the other languages supported by OpenFaaS Kotlin isn't tied to a single platform (Kotlin runs on [JVM](https://kotlinlang.org/docs/reference/server-overview.html), [JS](https://kotlinlang.org/docs/reference/js-overview.html), and [Native](https://kotlinlang.org/docs/reference/native-overview.html) platforms). Kotlin Native (based on [LLVM](https://llvm.org/)) can create self contained binaries (starting with version 0.7), and [interop with C libraries](https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md). Interop with Kotlin Native also extends to [JS](https://github.com/JetBrains/kotlin-native/tree/master/samples/html5Canvas) and Python (with [Python extensions](https://github.com/JetBrains/kotlin-native/tree/master/samples/python_extension) only).

There is a general overview of Kotlin Native that can be found in [this video](https://www.youtube.com/watch?v=3K3oQ22nqfo). This **Talking Kotlin** [podcast](http://talkingkotlin.com/kotlin-native-with-nikolay-igotti/) provides an alternative overview of Kotlin Native (from the Kotlin Native team lead). For memory management Kotlin Native programs and libraries use ARC (with cyclic collector), while manual memory is used for C interop (on Kotlin Native only). Other Kotlin platforms (Kotlin JS, Kotlin JVM) use Garbage Collection. Kotlin Native has some server-side samples ([non blocking echo server](https://github.com/JetBrains/kotlin-native/tree/master/samples/nonBlockingEchoServer), and [socket](https://github.com/JetBrains/kotlin-native/tree/master/samples/socket)).

## Context

In order for Kotlin Native to be supported by OpenFaaS the following would be needed:

- Getting started guide for using Kotlin Native with OpenFaaS
- Kotlin Native support added to the [OpenFaaS CLI](https://github.com/openfaas/faas-cli) tool (will require the platform to be passed as a argument)
- Kotlin Native APIs (if needed)
- General Kotlin Native documentation (as needed)
- Support for the Kotlin Native runtime and standard library as part of the OpenFaaS bootstrapping process

By providing all the key things needed above this would allow Kotlin Native programs to be executed/managed by OpenFaaS, and make it possible to use Kotlin for **Serverless** development on cloud platforms without the key performance issues encountered when [using the JVM](https://blog.travelex.io/blazing-fast-microservice-with-go-and-lambda-d30d95290f28) (high memory usage, large program code size, long cold startup times etc). Also OpenFaas would provide the following advantages for Kotlin Native Serverless programs:

- Easy and quick deployment
- Freedom to use any software (frameworks/toolkits/libraries) that is suitable for Serverless development
- Easy management of programs via the web dashboard
- Straightforward system for debugging running programs without going through extra hoops

**Comment by iyovcheva** [comment] 2018-06-04 14:28
@napperley Thank you for opening this issue.
I think it fits better in the [templates](https://github.com/openfaas/templates) repo, but is ok to stay here.

If you're interested in creating a Kotlin template, your help is welcome.

@alexellis any thoughts on that?

**Comment by iyovcheva** [comment] 2018-06-04 14:28
Derek add label: proposal

**Comment by iyovcheva** [comment] 2018-06-04 14:28
Derek add label: help wanted

**Comment by iyovcheva** [comment] 2018-06-04 16:34
@napperley you can create your own custom template for Kotlin following these [docs]( http://docs.openfaas.com/cli/templates/#40-customise-a-template) and then share the repo.

If you have any questions or need support on that, please reach out.

**Comment by affix** [comment] 2018-06-06 22:01
@iyovcheva I believe that the best way is to have a community template and add it to the community.md file

**Comment by iyovcheva** [comment] 2018-06-11 08:55
Closing this as the issue is raised in `openfaas/template`.

**Comment by iyovcheva** [comment] 2018-06-11 08:55
Derek close

**Closed by iyovcheva** 2018-06-11 08:55 UTC
Labels: help wanted, proposal
