### ISSUE TITLE
Support: async mode mode appeared to hang

### ISSUE THREAD

**Issue by heroic** [openfaas/faas#773] opened 2018-07-17 03:00 UTC
I set up open faas on GKE, and when I submit a batch of tasks to be executed asynchronously, the request times out and throws 502. At this moment a synchronous call continues to work.

I am taking a guess that the NAT streaming is causing an issue here, not sure how to be sure, or to solve.

## Expected Behaviour
The async request should be accepted and executed in the background.

## Current Behaviour
The async request does not finish and times out with a 502.

## Steps to Reproduce (for bugs)
1. Deploy OpenFaas on GKE.
2. Add/Remove a few nodes, scale the pods up and down.
3. Submit an async request.

## Context
I use openfaas to execute some long running jobs, which are generated in bulk by some user actions, such as a user uploading a set of pdf files.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ): GKE

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? GKE

* Operating System and version (e.g. Linux, Windows, MacOS): GKE

* Link to your project or a code example to reproduce issue: http://35.200.173.222/async-function/ultron

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have: Timeouts are all set to 300s. This seems to be happening in the gateway pods. Restarting gateway pods seems to solve the problem.

**Comment by alexellis** [comment] 2018-07-17 07:35
Hi @heroic GKE is a very well tested configuration for us, I can't think of any scenario where any part of OpenFaaS would hang when calling a function in async mode. Therefore can you please do a couple of things for us:

Work through the troubleshooting guide

* [ ] retrieve the logs of the queue worker and gateway, save them into a Gist (send link to this issue)
* [ ] try to reproduce the issue with one of the functions in the store like figlet

Failing all of that, please share your function code with us which may be the cause of the issue.

Also I don't know if this is relevant, but perhaps you should not be manually scaling Pods, which Pods in particular are you "scaling"?

> Add/Remove a few nodes, scale the pods up and down.

Alex

**Comment by heroic** [comment] 2018-07-17 08:34
@alexellis What I meant by scaling was, apply a CPU limit and kubectl replace the pods.

I'll share the logs when the hang happens again.

**Comment by alexellis** [comment] 2018-07-21 21:12
Which pods did you replace?

Alex

**Comment by alexellis** [comment] 2018-07-21 21:13
I'll close this issue for now, but please keep commenting and if you get the data points re-open it at any time.

Alex

**Closed** 2018-07-21 21:12 UTC
