### ISSUE TITLE
freeze on downloading APKINDEX.tar.gz

### ISSUE THREAD

**Issue by mjafarpour** [openfaas/faas#427] opened 2017-12-08 23:11 UTC
Hi,
I try nodejs sample from official document and have this problem:
freeze build process on fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
step.
Network connection is OK.

output:
[0] > Building: callme.
Clearing temporary build folder: ./build/callme/
Preparing ./callme/ ./build/callme/function
Building: callme with node template. Please wait..
Sending build context to Docker daemon 10.24 kB
Step 1/21 : FROM node:8.9.1-alpine
 ---> 8bcb66e2abe9
Step 2/21 : RUN addgroup -S app && adduser -S -g app app
 ---> Running in 6751f6247a53
 ---> 9513857e469a
Removing intermediate container 6751f6247a53
Step 3/21 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.6.9/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Running in bce9ceee6e2e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz

**Comment by alexellis** [comment] 2017-12-09 02:27
Thank you for using OpenFaaS.

I have to say I used this today so I suspect it's something else that's wrong. This is a standard Alpine Linux command. I'm going to close the issue because I can't reproduce it but feel free to keep commenting.

What country are you connecting from?

**Closed by alexellis** 2017-12-09 02:27 UTC

**Comment by mjafarpour** [comment] 2017-12-09 04:45
My country is iran.

**Comment by mjafarpour** [comment] 2017-12-09 20:12
OK thanks, i try again the build command after some and this problem is fixed. 
But after the end build step successfully according to sample, i run Deploy command as below line : 
`faas-cli deploy -f callme.yml `
and get this error : 

`Deploying: callme.
Error removing existing function: Delete http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused, gateway=http://127.0.0.1:8080, functionName=callme
Is FaaS deployed? Do you need to specify the --gateway flag?
Post http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused`

note: I didn't run push step because i run this on my laptop.

**Comment by alexellis** [comment] 2017-12-10 00:31
Hi glad you got that working :-) looks like the internet connection getting in the way. These sites I believe are in the US. So did you deploy OpenFaaS yet?

**Comment by mjafarpour** [comment] 2017-12-11 04:54
Thanks for your attention.

**Comment by alexellis** [comment] 2017-12-11 05:17
Generally this error means you didn't deploy OpenFaaS

> dial tcp 127.0.0.1:8080: getsockopt: connection refused,

Can you check and try again?
