### ISSUE TITLE
Swarm with multiple nodes not working as expected

### ISSUE THREAD

**Issue by linuxjuggler** [openfaas/faas#1092] opened 2019-02-19 08:03 UTC
Following the instructions to deploy OpenFaas on a swarm with multiple nodes returns "Error pulling metrics from provider/backend. Status code: 502" which can be read from the console tab within the browser developer tools.

## Expected Behaviour
The UI should not have any problem, and the system should work.

## Current Behaviour
1. The UI returns a hidden error which can be read from the console, which indicates that the services have some problems communicating with each other.

![screen shot 2019-02-19 at 10 32 57 am](https://user-images.githubusercontent.com/27624/52997507-caaeb580-3431-11e9-80f4-8f5b8646f232.png)

2. The CLI will also throw an error when you try to log in:

```
Server returned unexpected status code: 500 - Error pulling metrics from provider/backend. Status code: 502
```

## Steps to Reproduce (for bugs)
1. Create a small swarm with three nodes; they are all managers

![screen shot 2019-02-19 at 9 43 19 am](https://user-images.githubusercontent.com/27624/52997680-46a8fd80-3432-11e9-9440-c68d09d20dc6.png)

There is a hardware firewall between them with the following rules:
* Allow all Outbound connections.
* Allow Inbound ports: 22, 8080, 53, 4789, 2377, 2376, 7946

![screen shot 2019-02-19 at 11 09 15 am](https://user-images.githubusercontent.com/27624/52999442-d2248d80-3436-11e9-95a7-7031f525aaf9.png)

2. Add a small VPS in front of them with nginx installed and configured as a load balancer (with SSL termination using CloudFlare) which will load the requests between the three managers.

```
upstream swarm {
    server     x.x.x.x:8080;
    server     x.x.x.x:8080;
    server     x.x.x.x:8080;
}

server {
    listen     80;
    listen     443 ssl http2 default_server;

    server_name x.x.x.x;

    ssl        on;
    ssl_certificate         /etc/nginx/ssl/certificate.pem;
    ssl_certificate_key     /etc/nginx/ssl/certificate.key;

    location / {
        proxy_pass http://swarm;
    }
}
```
3. Execute the deploy command `./deploy_stack.sh` and wait a few sec for all the services to run.

![screen shot 2019-02-19 at 9 44 10 am](https://user-images.githubusercontent.com/27624/52997880-cdf67100-3432-11e9-87e4-e4d104caccbd.png)

4. Check the UI and log in, everything should work great, except the error you will notice whenever you try to deploy a function, in my case I get "bad gateway" response from Cloudflare http://d.zah.me/n56q1y

5. Look at the developer console you will notice the error:

![screen shot 2019-02-19 at 10 32 57 am](https://user-images.githubusercontent.com/27624/52997507-caaeb580-3431-11e9-80f4-8f5b8646f232.png)

6. You try to login via the CLI, and you get the error:

```
Server returned unexpected status code: 500 - Error pulling metrics from provider/backend. Status code: 502
```

7. Looking at the gateway logs you will get the follwoing message, which indicate that the gateway cant find `faas-swarm` service:

```
func_gateway.1.sb0elhkc4kdw@master    | 2019/02/19 06:39:59 Forwarded [GET] to /system/functions - [502] - 0.009134 seconds func_gateway.1.sb0elhkc4kdw@master    | 2019/02/19 06:40:01 Get http://faas-swarm:8080/system/functions: dial tcp: lookup faas-swarm on 127.0.0.11:53: no such host func_gateway.1.sb0elhkc4kdw@master    | 2019/02/19 06:40:03 error with upstream request to: /system/functions, Get http://faas-swarm:8080/system/functions: dial tcp: lookup faas-swarm on 127.0.0.11:53: no such host
```

8. Running the command `docker stack ps func` you will notice that `faas-swarm` and `gateway` are not on the same node

![screen shot 2019-02-19 at 9 39 35 am](https://user-images.githubusercontent.com/27624/52998214-c8e5f180-3433-11e9-871a-f3a89b4d84db.png)

`faas-swarm` on master 2, meanwhile `gateway` on master 1.

**PS**: One thing I might need to test more further is having a swarm from one manager and two workers.

## Context
Am sure this is not how the system should work if I switch all of this to only a swarm from one node it will work without any problem since they will all be on the same node.
The [lab1](https://github.com/openfaas/workshop/blob/master/lab1.md) assumes that you are going to use a swarm from one node.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.4.0-142-generic x86_64),
on a Scaleway VPS (https://github.com/scaleway/image-ubuntu), I am using a small version they have built specifically for small servers

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
Steps to Reproduce section should have all the logs I've collected

**Comment by alexellis** [comment] 2019-02-19 08:24
Hi,

Thanks for your interest in OpenFaaS.

I am unaware of any issues with Swarm or multiple node support.

What I've done is to spend some time to set up a 3-node cluster on Packet.net and take some screenshots to demonstrate that this worked without error:

<img width="1048" alt="screenshot 2019-02-19 at 08 17 41" src="https://user-images.githubusercontent.com/6358735/52999886-e0ff4600-341e-11e9-87bc-f017fc4f74d6.png">

<img width="1670" alt="screenshot 2019-02-19 at 08 16 04" src="https://user-images.githubusercontent.com/6358735/52999887-e0ff4600-341e-11e9-86df-3f9ff296e20a.png">

Here's my thoughts:

I can't reproduce any multi-node issue in Swarm with OpenFaaS, so it points to your environment:

Could I make a suggestion? Perhaps using DigitalOcean's Kubernetes service would work out better for you? This is a cheap and effective service and their offering is reliable.

What you may have is an issue with your cloud provider (Scaleway's kernel image). What Image did you use there? They have a "Docker" image which may work better.

Your Nginx configuration could also be part of the problem, or the firewall rules you have picked.

I'm going to close this issue since it is not a problem with OpenFaaS, however if you can how that this issue is a problem with OpenFaaS we'll prioritise it and fix it.

* Try DigitalOcean

https://www.openfaas.com/blog/digitalocean-one-click/
https://www.openfaas.com/blog/deploy-digitalocean-ansible/
https://blog.alexellis.io/digitalocean-kubernetes-engine/

I can suggest other clouds, but if you're using Scaleway, I assume that economy is important?

* Use Scaleway support

* Use the Docker Forum for support

https://forums.docker.com

Good luck

Alex

**Closed by alexellis** 2019-02-19 08:24 UTC

**Comment by linuxjuggler** [comment] 2019-02-19 08:40
hey @alexellis and thanks for the reply.

Am not sure how your environment which consists of 1 manager and two workers are the same as the one I've described in my issues which is a cluster of three managers not one.

anyway, thanks for your notes and I'll check them.

**Comment by linuxjuggler** [comment] 2019-02-19 08:55
Also @alexellis can help me with this and provide me with the position of each service using the command `docker stack ps func` so we can see where the `gateway` and the `faas-swarm` services are located.

This would provide more insight into the issue (at least for me).

Thanks

**Comment by linuxjuggler** [comment] 2019-02-19 08:59
Also, as I mentioned in my tweet yesterday, the **same setup with only one node works** btw, so am sure it's not the kernel which causes the issue.

and if it was a problem in the Firewall, and forgive me to mention that the docs never mentioned anything about special ports that should be open for the faas to work, except the one needed for docker swarm.

Anyway, thank you for your help and have a nice day.

**Comment by linuxjuggler** [comment] 2019-02-19 09:09
Never mind guys, thanks for all the help.

I'll go over all the notes that you have mentioned and see what is the issue.

Thanks again,

Have a nice day

**Comment by linuxjuggler** [comment] 2019-02-19 09:23
I found the issue. The Firewall should have the port `53` open for both TCP/UDP 

![screen shot 2019-02-19 at 12 17 07 pm](https://user-images.githubusercontent.com/27624/53003638-7959f280-3440-11e9-99b8-1a372e0752fd.png)

![screen_shot_2019-02-19_at_12_22_26_pm](https://user-images.githubusercontent.com/27624/53003944-29c7f680-3441-11e9-8c08-bb34383c1c1f.png)


Which is something the docs didn't mention, the only thing it has related to [swarm ports](https://docs.openfaas.com/deployment/docker-swarm/#12-join-any-workers-you-need), and I suggest that the docs say more information about the required ports for the system to work.

Sorry, @alexellis  if I was rude to you or anyone.

Have a nice day.

**Comment by alexellis** [comment] 2019-02-20 09:31
Great to see that you figured it out 👍 The OpenFaaS docs link to the Swarm documentation that details the ports needed etc. Maybe this will help another user in the future. 

Alex

**Comment by alexellis** [comment] 2019-02-20 09:31
Derek lock: resolved
