### ISSUE TITLE
Support question: help with error stan: connection closed

### ISSUE THREAD

**Issue by stephrobert** [openfaas/faas#1169] opened 2019-04-25 12:34 UTC
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

When i submit a async call with docker log-driver to syslog

```
echo -n "" | faas-cli invoke long-task --async
Server returned unexpected status code: 500 - stan: connection closed
```

Since with log-driver set to json-file 

```
echo -n "" | faas-cli invoke long-task --async
Function submitted asynchronously.
```

## Expected Behaviour
Add to documentation this limitation. We decided to use fluentd in place of syslog

## Steps to Reproduce (for bugs)
Just change the documentation 

## Your Environment

**FAAS-CLI version** :
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

Gateway
 uri:     https://gateway-openfaas.systema.cloud.socrate.vsct.fr
 version: 0.10.2
 sha:     bfa869ec8c0c04c26c5b0ed434bc367e712dcaef
 commit:  Revert docker tag bump to 0.10.0

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.7.0 
 sha:           ab9b56c0760eadba05762fa53dbe99d890bc9e19

**docker version**

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**kubectl version** 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS Linux release 7.6.1810 (Core)

**Comment by alexellis** [comment] 2019-04-25 13:06
Hi thanks for the report.

This is the first time I've heard of an error like this. Let me ping the NATS team to see if they can make a suggestion.

Feel free to look into it at your end or with your alternative logging driver (fluentd) - did you see anything in the logs of the various services?

@kozlovic do you have any thoughts?

@padiazg I believe you were using fluentd, did you get this error?

Alex

**Comment by alexellis** [comment] 2019-04-25 13:07
@stephrobert 

> Steps to Reproduce (for bugs)

Please can you give a list of exact (repeatable) step-by-step instructions as requested by the issue template so that anyone (especially those who don't use fluentd with your config) can reproduce the issue and/or investigate it?

**Comment by alexellis** [comment] 2019-04-25 13:11
Just as a thought here.. doesn't GKE use fluentd? Many of us in the community have or do run OpenFaaS on GKE and don't have any issues. My suspicion is that you may have an unrelated issue caused by restarting NATS or using an old version of OpenFaaS.

**Comment by kozlovic** [comment] 2019-04-25 15:18
@alexellis Not sure how I can help here. It is possible that the connection has been closed due to pings or that you have explicitly closed the connection and then attempt to publish or subscribe, etc..

**Comment by alexellis** [comment] 2019-04-25 15:46
Original poster here suspects that there is some relationship between logging drivers and NATS. I and several people in the community are running NATS with fluentd without issues so wondered if you had seen anything similar before. 

All the components have been updated to retry and reconnect unless a very old version is in use?

Alex

**Comment by stephrobert** [comment] 2019-04-25 20:15
> @stephrobert
> 
> > Steps to Reproduce (for bugs)
> 
> Please can you give a list of exact (repeatable) step-by-step instructions as requested by the issue template so that anyone (especially those who don't use fluentd with your config) can reproduce the issue and/or investigate it?

After install docker with syslog as log-driver, kubernetes  and openfaas (with faas-netes) i tried to launch async function with the result said before. As we get direct log with syslog, i decided to remove syslog as log-driver and when i launched again the async function the result was ok. I repeated on another stack with the same result.

**Comment by stephrobert** [comment] 2019-04-25 20:47
I tried on my raspberry cluster at home and i cant reproduce this issue.

**Comment by alexellis** [comment] 2019-05-06 20:32
Derek close

**Comment by alexellis** [comment] 2019-05-06 20:33
Hi, I'm closing this now, but I'll reopen if you can find a way to reproduce the error consistently.

For ad-hoc support please use Slack

Alex


--
Join Slack to connect with the community
https://docs.openfaas.com

**Closed by alexellis** 2019-05-06 20:32 UTC
Labels: support
