### ISSUE TITLE
Unexpected output from Python 3 function

### ISSUE THREAD

**Issue by blaskovicz** [openfaas/faas#621] opened 2018-04-01 14:09 UTC
I've deployed the following function to OpenFaaS via Docker Swarm and faas-cli: https://github.com/blaskovicz/rmb-to-usd.  After using it for a few days on and off via [my website](https://www.carlyzach.com/functions/rmb-to-usd), I noticed that it was no longer responding correctly.
 
After looking at the service in `docker service ps` it seemed to be up; upon scaling it down to 0 and then back up to 1, it started responding with the correct output. I was wondering if you could help provide any insight into what went wrong? 

## Expected Behaviour

The function should respond with a JSON body:
```sh
$ echo "hi" | faas-cli invoke rmb-to-usd -                                                                                                                   
{"id": "unprocessable_entity", "message": "the request body was malformed"}
```

## Current Behaviour

From the `faas-cli`, I receive something strange, statistics output, perhaps?
```sh
$ echo "hi" | faas-cli invoke rmb-to-usd                                                                                                                        
        1         1         3
```

From a POST to the function via the gateway, I got a similar response body:
```
        0         1        24
```

## Possible Solution

After restarting the function (`docker service scale rmb-to-usd=0 && docker service scale rmb-to-usd=1`), the function again began to service requests correctly.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```sh
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm.

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04 LTS

* Link to your project or a code example to reproduce issue:
   * Code: https://github.com/blaskovicz/rmb-to-usd
   * Site: https://www.carlyzach.com/functions/rmb-to-usd

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

State before function restart:
```sh
$ docker service ps rmb-to-usd 
ID                  NAME                IMAGE                              NODE                DESIRED STATE       CURRENT STATE         ERROR                              PORTS
u2cn200qd014        rmb-to-usd.1        127.0.0.1:5000/rmb-to-usd:latest   z      Running             Running 3 days ago                                       
axrzewhs2dip         \_ rmb-to-usd.1    127.0.0.1:5000/rmb-to-usd:latest   z      Shutdown            Failed 3 days ago     "starting container failed: No…"   
pety5payl7l0         \_ rmb-to-usd.1    127.0.0.1:5000/rmb-to-usd:latest   z      Shutdown            Failed 3 days ago     "No such container: rmb-to-usd…"   
9muw046ek71y         \_ rmb-to-usd.1    127.0.0.1:5000/rmb-to-usd:latest   z      Shutdown            Failed 3 days ago     "No such container: rmb-to-usd…"   
4n09olyall8m         \_ rmb-to-usd.1    127.0.0.1:5000/rmb-to-usd:latest   z      Shutdown            Shutdown 3 days ago                                      
iw6kv16pb137         \_ rmb-to-usd.1    127.0.0.1:5000/rmb-to-usd:latest   z      Shutdown            Shutdown 3 days ago                                      
```

**Comment by rgee0** [comment] 2018-04-01 14:28
This is something I definitely haven't seen/experienced.  The unexpected output looks like the output from the `func_wordcount` sample function.

What happened 3 days ago? What are those failed state error messages alluding to?

Do the gateway logs still hold the info about the requests that returned the unexpected output?

Is this a isolated occurrence or are you able to reproduce it?

**Comment by rgee0** [comment] 2018-04-01 14:33
Derek set title: Unexpected output from Python 3 function

**Comment by blaskovicz** [comment] 2018-04-01 14:51
3 days ago I did reboot the underlying system, but my other functions, [playground-golang](https://github.com/blaskovicz/playground-golang) and `func_markdown` rebooted and had no issues:

```sh
$ uptime
 10:49:05 up 3 days, 12:39,  2 users,  load average: 1.17, 1.03, 0.90
```

```
$ zgrep --color rmb-to-usd /var/log/syslog.*
/var/log/syslog.4.gz:Mar 28 21:43:15 z dockerd[1580]: time="2018-03-28T21:43:15.056693057-04:00" level=error msg="fatal task error" error="No such container: rmb-to-usd.1.9muw046ek71y9lrur75o5cwxb" module="node/agent/taskmanager" node.id=75e271bvg2t57wusmqn0groyo service.id=chk4e56wfhi2zq7rmgumbryc7 task.id=9muw046ek71y9lrur75o5cwxb
/var/log/syslog.4.gz:Mar 28 22:10:15 z dockerd[1786]: time="2018-03-28T22:10:15.038716739-04:00" level=error msg="fatal task error" error="No such container: rmb-to-usd.1.pety5payl7l044vvvfrsxz02o" module="node/agent/taskmanager" node.id=75e271bvg2t57wusmqn0groyo service.id=chk4e56wfhi2zq7rmgumbryc7 task.id=pety5payl7l044vvvfrsxz02o
/var/log/syslog.4.gz:Mar 28 22:10:20 z dockerd[1786]: time="2018-03-28T22:10:20.679675495-04:00" level=warning msg="failed to deactivate service binding for container rmb-to-usd.1.1w21v41dk3pu6agto8nmkvkmf" error="No such container: rmb-to-usd.1.1w21v41dk3pu6agto8nmkvkmf" module="node/agent" node.id=75e271bvg2t57wusmqn0groyo
/var/log/syslog.4.gz:Mar 28 22:10:31 z dockerd[1786]: time="2018-03-28T22:10:31.852767657-04:00" level=warning msg="failed to deactivate service binding for container rmb-to-usd.1.2ekqeqj35a8577s4jqx2fk5u5" error="No such container: rmb-to-usd.1.2ekqeqj35a8577s4jqx2fk5u5" module="node/agent" node.id=75e271bvg2t57wusmqn0groyo
```

The gateway logs don't show anything useful, they seem to be the same for yesterday (non-working) and today (working after restart):
```sh
$  docker service logs func_gateway
func_gateway.1.kk78rwblgk3z@z    | 2018/03/31 21:29:37 > Forwarding [POST] to /function/rmb-to-usd
func_gateway.1.kk78rwblgk3z@z    | 2018/03/31 21:29:37 GetHeaderCode 200
func_gateway.1.kk78rwblgk3z@z    | 2018/03/31 21:29:37 < [http://faas-swarm:8080/function/rmb-to-usd] - 200 took 0.018241 seconds
func_gateway.1.kk78rwblgk3z@z    | 2018/04/01 02:29:06 > Forwarding [POST] to /function/rmb-to-usd
func_gateway.1.kk78rwblgk3z@z    | 2018/04/01 02:29:06 GetHeaderCode 200
func_gateway.1.kk78rwblgk3z@z    | 2018/04/01 02:29:06 < [http://faas-swarm:8080/function/rmb-to-usd] - 200 took 0.004942 seconds
```

**Comment by rgee0** [comment] 2018-04-01 15:32
Thanks for the further info.

Do you know if the unexpected output was extant for the full period from 3 days ago until the `service scale` activity today?  Or was the function confirmed as working following your reboot and switched to unexpected output some time later?  If the latter what time would that be?

My suspicion (and its no more than that currently) is that this could relate to a Docker feature which has been fixed in later versions.  Would pulling Docker up to something more recent be a possibility?

**Comment by blaskovicz** [comment] 2018-04-01 15:43
@rgee0 I didn't test the function immediately following the host reboot, but I would assume it was broken after that time up until I `docker service scale`d.

I could try updating docker. Seeing as 17.09 isn't that old, what issue do you think is causing this?

https://docs.docker.com/release-notes/docker-ce/#17091-ce-2017-12-07

**Comment by rgee0** [comment] 2018-04-01 16:52
Whats concerning me is that your invocation seems to be hitting a totally separate function.  This could be that the wordcount image has been tagged as your rmb image (unlikely and wouldn't be fixed by a scale operation), or that the service definitions contain stale information, or something else that I'm yet to consider/uncover.

Although this is the first time I've seen this reported on OpenFaaS, I have seen issues with Docker, which are said to be fixed in 17.12 and greater, where the services would have issues with IP addresses.  My supposition at this stage is that when the rmb service came back up following the reboot it was provided an IP address which was being used by wordcount, or that the rmb service information was stale and wordcount was allocated the IP address that was in the stale rmb information.  

Of course its difficult to fully diagnose & test the cause, and test the fix via github issues so there's a bit of a leap here.  We could try rebooting your host again to see if the issue can be reproduced - this could possibly impact a different set of services that we could then interrogate with `service inspect`.  Alternatively we might fail to reproduce.

Out of interest, are those invoke commands in the initial comment copy and pasted? How are you hitting the gateway on a bespoke port without supplying `-g`?  Also, to save me making further assumptions could we get a view of your `docker service ls` output, please?

**Comment by alexellis** [comment] 2018-04-03 16:16
My guess is that this is either an issue with the Docker version you're using or that your Docker registry container wasn't started when you rebooted the machine.

Did you run your local registry with a --restart=always flag?

I can see from the output from docker service ps that you have had some issues with your local registry.

I'd be inclined to close this issue - it doesn't appear to be reproducible, but if you do come up with clear steps for reproducing the problem let us know and we can look into it.

**Comment by blaskovicz** [comment] 2018-04-08 18:39
I can see it being related to the registry being flaky. Earlier today I noticed it was in a bad state and had to scale it to 0 then back up to 1.

```
$ docker service inspect --pretty registry                                                                                                         

ID:             u45blt5vyvhke12qvppt0qob2
Name:           registry
Service Mode:   Replicated
 Replicas:      1
Placement:
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         registry:2@sha256:672d519d7fd7bbc7a448d17956ebeefe225d5eb27509d8dc5ce67ecb4a0bce54
Resources:
Endpoint Mode:  vip
Ports:
 PublishedPort = 5000
  Protocol = tcp
  TargetPort = 5000
  PublishMode = ingress
```

I think when I originally deployed openfaas, I changed the default published port:

```
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,7 +2,7 @@ version: "3.3"
 services:
     gateway:
         ports:
-            - 8080:8080
+            - 8082:8080
```

```
$ docker service ls
9u4pxjv4m6cl        func_alertmanager                    replicated          1/1                 prom/alertmanager:v0.15.0-rc.0                     
qavk0a348lvn        func_base64                          replicated          1/1                 functions/alpine:latest                            
6iru17vgguf0        func_echoit                          replicated          1/1                 functions/alpine:latest                            
6lfj66ylje8l        func_faas-swarm                      replicated          1/1                 functions/faas-swarm:0.2.2                         
wf9zw1g9lukb        func_gateway                         replicated          1/1                 functions/gateway:0.7.3                            *:8082->8080/tcp
hen7ixpduf7l        func_hubstats                        replicated          1/1                 functions/hubstats:latest                          
xby7mtg5i0qi        func_markdown                        replicated          1/1                 functions/markdown-render:latest                   
m3judmv4evz2        func_nats                            replicated          1/1                 nats-streaming:0.6.0                               
j1s8klbyfv8c        func_nodeinfo                        replicated          1/1                 functions/nodeinfo:latest                          
joujjdk2awoz        func_prometheus                      replicated          1/1                 prom/prometheus:v2.2.0                             *:8083->9090/tcp
viq7fr588o40        func_queue-worker                    replicated          1/1                 functions/queue-worker:0.4                         
i5eadsxd7xqn        func_wordcount                       replicated          1/1                 functions/alpine:latest                            
gunbgjl4qfp6        playground-golang                    replicated          1/1                 127.0.0.1:5000/playground-golang:latest            
u45blt5vyvhk        registry                             replicated          1/1                 registry:2                                         *:5000->5000/tcp
```

**Comment by alexellis** [comment] 2018-04-09 01:41
I’m going to close the issue. Please comment again if needed.

**Closed by alexellis** 2018-04-09 01:41 UTC
Labels: area/swarm, question, support
